# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  none

pool:
  name: default
variables:
  rgname: "yamlrg"
  loc: "eastus"
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'azure connection'
    ScriptType: 'InlineScript'
    Inline: 'New-AzResourceGroup -Name $(rgname) -location $(loc)'
    azurePowerShellVersion: 'LatestVersion'